export {
  createContext,
  Fragment,
  useContext,
  type NativeChild,
  type NativeComponent,
  type NativeElement,
  type NativeElementType,
  type NativeKey,
} from '@eclipsa/native-core'
export {
  bootNativeApplication,
  createElement,
  defineNativeComponent,
  getNativeRuntime,
  getNativeMap,
  h,
  mountNativeApplication,
  peekNativeRuntime,
  resolveNativeElementType,
  setNativeMap,
  type DefinedNativeComponent,
  type MountedNativeApplication,
  type NativeApplicationInput,
  type NativeMap,
  type NativeMapModule,
  type NativeRuntime,
  type NativeRuntimeEvents,
  type NativeRuntimeRenderer,
} from './runtime.ts'
